Replace deprecated `get_cmap` and `register_cmap` calls with `colormaps` methods.
1313e/CMasher pull request #52
Opened 2023-08-02 16:34 UTC by blakeNaccarato

Fixes #43. There were further deprecations of the use of `mplcm.get_cmap` and `mplcm.register_cmap` which I have replaced with their recommended modern calls to `colormap.get_cmap` and `colormap.register`, respectively.

2023-08-02 16:38 UTC, blakeNaccarato commented on cmasher/tests/test_utils.py
I opted for the `plt.colormaps['name']` call here instead of `plt.colormaps.get_cmap('name')` in the tests, assuming this should test the stricter case of the cmaps already being registered, and if they aren't, the test will break on `KeyError`.

2023-08-02 16:53 UTC, blakeNaccarato commented on cmasher/tests/test_utils.py
Everywhere else I use the equivalent `plt.colormaps.get_cmap(...)` call which additionally checks if `...` is already an instance of a colormap and returns it. The dict-like call would break here, complaining of an unhashable type.

It may be the case that `colormaps.register` could be replaced by dict-like key setting on `colormaps`, but I figured it was a bridge too far.

2023-08-02 17:43 UTC, neutrinoceros requested changes
cmasher currently requires `matplotlib>=2.2.4`, so if you want to use modern API, you need to make it conditional or to bump the minimal supported version.

As is, this breaks `import cmasher` on Python 3.7 (for which the latest compatible matplotlib version is 3.5.3).
```shell
python -c "import cmasher"
```
```python-traceback
Traceback (most recent call last):
  File "/Users/robcleme/dev/CMasher/cmasher/utils.py", line 1110, in import_cmaps
    register_cmap(cm_name, rgb)
  File "/Users/robcleme/dev/CMasher/cmasher/utils.py", line 1190, in register_cmap
    cm_type = get_cmap_type(cmap_mpl)
  File "/Users/robcleme/dev/CMasher/cmasher/utils.py", line 858, in get_cmap_type
    cmap = plt.colormaps.get_cmap(cmap)
AttributeError: 'ColormapRegistry' object has no attribute 'get_cmap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/robcleme/dev/CMasher/cmasher/__init__.py", line 14, in <module>
    from . import utils
  File "/Users/robcleme/dev/CMasher/cmasher/utils.py", line 1444, in <module>
    import_cmaps(path.join(path.dirname(__file__), 'colormaps'))
  File "/Users/robcleme/dev/CMasher/cmasher/utils.py", line 1127, in import_cmaps
    % (cm_name, error))
ValueError: Provided colormap 'amber' is invalid! ('ColormapRegistry' object has no attribute 'get_cmap')
```

2023-08-02 17:52 UTC, blakeNaccarato commented
I see. Should I condition the `colormap` namespace usage (really just an instance of `ColormapRegistry`) on a `matplotlib` version check or a Python version check? Or perhaps even a check for the `get_cmap` attribute in `ColormapRegistry` and fallback to the `cm` namespace in its absence?

Also it's probably worth considering dropping Python 3.7 in the next release, since it went EOL last year. I'm assuming that should be undertaken in a separate PR and not pursued (or presumed) here.

2023-08-02 18:10 UTC, neutrinoceros commented
> Can you approve the test workflows so as I add commits I can see how the test matrix turns out? Or would you rather I run them in my own forked branch for now?

I'm not a maintainer of this repo. I cannot approve your runs

2023-08-02 22:22 UTC, blakeNaccarato commented
Alright, I'll try to find some further time to work these details into the PR. I appreciate the help, I haven't had the pleasure (heh) of working with long-lived library code before, and so haven't really had to mess around with version check semantics much.

I will convert to Draft until then, and yeah I'll just run CI in my own fork for the time being.

2023-08-07 03:45 UTC, blakeNaccarato commented
Okay, I see this will take a bit more work than I thought. I have run CI in my fork on the equivalent of the current tip of the master branch, and I see that CI is failing there. I think it's mostly `pytest-flake8` complaining, so I could probably suppress those to show just the proper tests.

In my local branch on 3.11, at least most tests pass. Only `test_standalone_rainforest`, `test_standalone_infinity`, and `test_cmap_file_txt` tests are failing, seemingly due to colormap name collisions. But they do fail even on tip of master, too. I could mark those `xfail` for now to suppress that as well.

I think I could work this PR up to a certain level by just trying, say, Python 3.8 and Python 3.11 in custom virtual environments on my machine, and implementing version checks as you recommended.

But I see that a separate PR would probably be needed to bring CI up to passing before any other PRs have a chance. @1313e, what do you think? A separate PR focusing on CI would probably look something like:

- Turn down the noise, especially `flake8-pytest`. You can always turn this back on in a separate PR campaign to get flake8 passing again.
- Drop Python 3.6 and 3.7 from CI
- Add Python 3.10 and 3.11 to CI, and to `setup.py` etc.
- Bump matplotlib a bit, too, perhaps
- `xfail` tests which are flaky for now, and consider figuring out what's going on there or deciding whether those tests are really "testing" anything (the ones failing w/r/to `rainforest` cmap)
- Consider dropping the custom `viscm` fork from dev requirements, if possible?

Should a PR like this target `master` directly? Or `dev`?

2023-08-07 16:28 UTC, blakeNaccarato commented
Oh, I see now that @neutrinoceros your earlier PR was merged to https://github.com/1313e/CMasher/tree/mpl_future_proofing, not `master`, my powers of observation are lacking 😅. I thought that it was merged in `master` already, so when I was still getting `DeprecationWarning` by installing from master, I've gone and duplicated that work (less effectively), that's my bad.

Okay, well I'll just chalk this up to getting experience with the codebase, but your branch tip works just fine regarding deprecations. So, maybe I will instead focus on the proposed CI/version changes above.

2023-08-07 16:59 UTC, closed without merging

2023-12-18 07:48 UTC, neutrinoceros commented
@blakeNaccarato This is now resolved with the release of CMasher 1.7
see https://github.com/1313e/CMasher/releases/tag/v1.7.0

2023-12-20 01:21 UTC, blakeNaccarato commented
Thanks for the heads up, and the guidance before!